# INTRODUCTION TO PYTHON FOR MACHINE LEARNING  QUIZ 

     Hello Hamoye Team,
     My name is Goodluck Olawale, an intern with Hamoye, and this is my code for the different questions in the quiz. Although i didn't perform up to expectation i was able to identify some mistakes i made due to the exam pressure and time constraint and i sincerely hope this would count. 
     Also your feebacks or comment would be very much appreciated.


In [29]:
#import the needed libraries
import pandas as pd
import math
import numpy as np

In [30]:
#to import the dataset into a dataframe using pandas
df=pd.read_csv('https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv')

# Question 1

In [31]:
#Question 1
A = [1,2,3,4,5,6]
B = [13, 21, 34]
A.append(B)
print(A)

[1, 2, 3, 4, 5, 6, [13, 21, 34]]


In [32]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]
A.extend(B)
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


# Question 2

In [33]:
#Question 2
np.eye(3) #not eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
print(np.array([[1,0,0],[0,1,0],[0,0,1]])) #notice the apprpriate syntax

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Question 3

In [36]:
# the fuel_type_code_pudl with the lowest average fuel_cost_per_unit_burned
df.groupby(['report_year','fuel_type_code_pudl'])['fuel_cost_per_unit_burned'].mean().idxmin()


(2000, 'waste')

# Question 4

In [37]:
#Standard deviation and 75th percentile for Fuel_mbutu_per_unit
df.describe() 

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

# Question 5

In [38]:
#The skew for fuel quanity burned
df.skew(axis=0)


utility_id_ferc1                  0.605070
report_year                       0.006953
fuel_qty_burned                  15.851495
fuel_mmbtu_per_unit               4.135217
fuel_cost_per_unit_burned        19.787440
fuel_cost_per_unit_delivered    105.014227
fuel_cost_per_mmbtu             171.675535
dtype: float64

In [39]:
# Kurtosis for fuel quanity burned
df.kurtosis(axis=0)

utility_id_ferc1                    1.088432
report_year                        -1.145656
fuel_qty_burned                   651.369450
fuel_mmbtu_per_unit                55.595695
fuel_cost_per_unit_burned         485.255851
fuel_cost_per_unit_delivered    11765.054226
fuel_cost_per_mmbtu             29489.132594
dtype: float64

# Question 6

In [40]:
df.isnull().sum()
df.shape
print(df.isnull().sum().max() / df.shape[0])

0.00609694136774718


# Question 7

In [41]:
df.groupby('fuel_type_code_pudl')['fuel_unit'].value_counts()
#Grouping the dataset with respect to fuel_type_code_pudl and finding its values_counts infers that the Categorical and mode imputation should be used


fuel_type_code_pudl  fuel_unit
coal                 ton           8438
                     mmbtu           52
                     mcf              5
                     bbl              1
gas                  mcf          11333
                     mmbtu           94
                     ton              4
                     bbl              2
nuclear              gramsU         464
                     kgU            110
                     mwhth          100
                     mwdth           95
                     mmbtu           34
oil                  bbl           7952
                     gal             81
                     mcf              7
                     ton              3
other                ton             77
                     bbl             42
                     mcf              9
                     gal              3
waste                ton            436
                     bbl              1
Name: fuel_unit, dtype: int64

# Question 8

In [42]:
df.corr()
#the table below shows that the fuel_qty_burned and fuel_cost_per_unit delivered have the 2nd and 3rd highest correlation to the fuel_cost_per_unit_burned


utility_id_ferc1  report_year  fuel_qty_burned  \
utility_id_ferc1                      1.000000     0.093323        -0.057447   
report_year                           0.093323     1.000000         0.012952   
fuel_qty_burned                      -0.057447     0.012952         1.000000   
fuel_mmbtu_per_unit                  -0.066946    -0.110853        -0.080946   
fuel_cost_per_unit_burned            -0.037863     0.013599        -0.018535   
fuel_cost_per_unit_delivered         -0.016414    -0.014043        -0.003551   
fuel_cost_per_mmbtu                   0.006122     0.010261        -0.001896   

                              fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
utility_id_ferc1                        -0.066946                  -0.037863   
report_year                             -0.110853                   0.013599   
fuel_qty_burned                         -0.080946                  -0.018535   
fuel_mmbtu_per_unit                      1.000000                  -0.010034   
fuel_cost_per_unit_burned               -0.010034                   1.000000   
fuel_cost_per_unit_delivered            -0.009039                   0.011007   
fuel_cost_per_mmbtu                     -0.005884                  -0.000437   

                              fuel_cost_per_unit_delivered  \
utility_id_ferc1                                 -0.016414   
report_year                                      -0.014043   
fuel_qty_burned                                  -0.003551   
fuel_mmbtu_per_unit                              -0.009039   
fuel_cost_per_unit_burned                         0.011007   
fuel_cost_per_unit_delivered                      1.000000   
fuel_cost_per_mmbtu                              -0.000109   

                              fuel_cost_per_mmbtu  
utility_id_ferc1                         0.006122  
report_year                              0.010261  
fuel_qty_burned                         -0.001896  
fuel_mmbtu_per_unit                     -0.005884  
fuel_cost_per_unit_burned               -0.000437  
fuel_cost_per_unit_delivered            -0.000109  
fuel_cost_per_mmbtu                      1.000000

# Question 9

In [43]:
#percentage change in fuel cost per unit burned in 1998 and 1994
mean_1994=df.groupby(['report_year','fuel_type_code_pudl'])['fuel_cost_per_unit_burned'].mean().loc[1994,'coal']
mean_1998=df.groupby(['report_year','fuel_type_code_pudl'])['fuel_cost_per_unit_burned'].mean().loc[1998,'coal']
percent_change=(mean_1998-mean_1994)/(mean_1994) *100
print('percent_change = ' ,percent_change)


percent_change =  -12.458551963280119


# Question 10

In [44]:
#report year with the highest average fuel_cost_per_unit_delivered
df.groupby('report_year')['fuel_cost_per_unit_delivered'].mean().sort_values().idxmax()

1997